export { default as MainPage } from "./mainpage"
export { default as Login } from "./login"
export { default as SignupForm } from "./Inscription"
export { default as Dash } from "./dashboardLawyer"
export { default as Orders } from "./ordersLawyer"
export { default as Clients} from "./clients"
export { default as Documents} from "./documentsLawyer"
export { default as Revenue} from "./revenueLawyer"
export { default as Suivi} from "./suiviCustomer"
export { default as Notifications} from "./notifications"
export { default as Request} from "./requestCustomer"
export { default as CaseCreate} from "./createCaseCustomer"
export { default as Notification} from "./notifClient"
export { default as Problems} from "./problems"
export { default as CaseDetails} from "./caseDetails"
export { default as profil} from "./profil"
export { default as Preinscription} from "./preinscription"
export { default as Messages} from "./messages"
